backend:
  name: github
  repo: ptxiaohong/captain-meow  # ← 替换这里
  branch: main  # 或 master

media_folder: "/Users/hongshize/猫猫船长个人网站/static/images/uploads"
public_folder: "/Users/hongshize/猫猫船长个人网站/public/images/uploads"

collections:
  - name: "posts"
    label: "博客文章"
    folder: "content/posts"
    create: true
    slug: "{{slug}}"
    format: "toml"
    fields:
      - { label: "标题", name: "title", widget: "string" }
      - { label: "发布日期", name: "date", widget: "datetime" }
      - { label: "分类", name: "categories", widget: "list", default: ["作品"] }
      - { label: "标签", name: "tags", widget: "list", default: ["作品"] }
      - { label: "封面图预览", name: "featuredImagePreview", widget: "image", required: false }
      - { label: "正文", name: "body", widget: "markdown" }

local_backend: true

